### ISSUE TITLE
emojis-keywords length and emoji-list length don't match 

### ISSUE THREAD

**Issue by jmtt89** [Kikobeats/emojis-keywords#14] opened 2020-09-29 15:49 UTC
Hi, in Readme says 

> Complete list of emoji shortcuts. The list is a 1:1 map of emojis-list.

but 

```
var keywords = require('emojis-keywords');
var emojis = require('emojis-list');

console.log(keywords.length) // <= 2477
console.log(emojis.length) // <= 3075
```

so obviously in not a 1:1 map, the others keywords not exist?

**Comment by Kikobeats** [comment] 2020-09-29 16:25
duplicate of https://github.com/Kikobeats/emojis-list/issues/10

**Closed as completed by Kikobeats** 2020-09-29 16:25 UTC
Labels: duplicate
